task: determined
goal: multiclass-classification

dataset: 
  dataname: FoldClassification
  csv_root: data/FoldClassification/splits/FoldClassification_{}.csv
  test_set: test_superfamily
  num_classes: 1195

project_name: EsmMHAGraphHead-FoldClassification-C300M-nofinetune

esm_config:
  model_name: esmc_300m
  model_size: 300M
  in_features: 960
  hidden_features: 960
  output_attentions: True
  contact_compression: mean_head
  num_hidden_layers: 30
  num_attention_heads: 15

head_config:
  head_name: EsmMHAGraphHead
  attention_features: 128
  attention_heads: 4
  dropout_rate: 0.1

fp16: True
quantized: False
peft: False

sweep_config:
  method: random
  parameters: 
    lr:
      value: 0.0005
    lr_scheduler_type:
      value: cosine
    num_train_epochs:
      value: 10
  metric:
    goal: "maximize"
    name: "eval/accuracy"

training_setting:
  per_device_train_batch_size: 8
  per_device_eval_batch_size : 8
  gradient_accumulation_steps: 2
  gradient_checkpointing: False
  criterion: ce
  
metric_for_best_model: accuracy
