task: determined
goal: token-classification

dataset: 
  dataname: SSP
  csv_root: data/ankh_ssp/splits/SSP_{}.csv
  test_set: test
  num_classes: 3

project_name: EsmMHAGraphHead-SSP-C300M-nofinetune

esm_config:
  model_name: esmc_300m
  model_size: 300M
  in_features: 960
  hidden_features: 960
  output_attentions: True
  contact_compression: mean_head
  num_hidden_layers: 30
  num_attention_heads: 15

head_config:
  head_name: EsmMHAGraphHead
  attention_features: 128
  attention_heads: 4
  dropout_rate: 0.1
  use_pooling: False

fp16: True
quantized: False
peft: False

sweep_config:
  method: random
  parameters: 
    lr:
      value: 0.0001
    lr_scheduler_type:
      value: cosine
    num_train_epochs:
      value: 20
  metric:
    goal: "maximize"
    name: "eval/accuracy"

training_setting:
  per_device_train_batch_size: 1
  per_device_eval_batch_size : 1
  gradient_accumulation_steps: 16
  gradient_checkpointing: False
  criterion: ce

metric_for_best_model: accuracy
