task: determined
goal: classification

dataset: 
  dataname: EC
  csv_root: data/EC/splits/EC_{}.csv
  num_classes: 538

project_name: EsmMHAGraphHead-EC-C600M-nofinetune

esm_config:
  model_name: esmc_600m
  model_size: 600M
  in_features: 1152
  hidden_features: 1024
  output_attentions: True
  contact_compression: mean_head
  num_hidden_layers: 36
  num_attention_heads: 18

head_config:
  head_name: EsmMHAGraphHead
  attention_features: 128
  attention_heads: 4
  dropout_rate: 0.1

fp16: True
quantized: False
peft: False

sweep_config:
  method: random
  parameters: 
    lr:
      value: 0.0001
    lr_scheduler_type:
      value: cosine
    num_train_epochs:
      value: 20
  metric:
    goal: "maximize"
    name: "eval/f1_max"

training_setting:
  per_device_train_batch_size: 4
  per_device_eval_batch_size : 8
  gradient_accumulation_steps: 4
  gradient_checkpointing: False
  criterion: 'bce'
  
metric_for_best_model: f1_max
